### ISSUE TITLE
New uploaded layer not available in the list

### ISSUE THREAD

**Issue by PierreLacroix** [fxi/map-x-shiny#1]
01.FEB.2016 tested on mapx.io/test by Pierre
New layer is uploaded from GeoJSON but is not available in the dropdown for creating a new view

**Comment by fxi** [comment]
Thanks.

There is a problem reaching pgrestapi service. Or postgres. I will check this.

**Comment by fxi** [comment]
That's a typo in the request for the service to reload. It's solved.
