### ISSUE TITLE
Problem opening MAP-X map on Afghanistan

### ISSUE THREAD

**Issue by PierreLacroix** [fxi/map-x-shiny#11]
<img width="504" alt="screen shot 2016-04-07 at 16 34 55" src="https://cloud.githubusercontent.com/assets/6863326/14354755/cd59d55e-fcde-11e5-8501-53297d948ec4.png">
https://www.mapx.io/app/w1/#sectionMap

**Comment by fxi** [comment]
Changes were not pulled to all workers. 

I've removed old workers and kept only w10 active for now. 

Thanks

**Comment by PierreLacroix** [comment]
Thanks a lot. At EITI-DRC they still have http://calc.grid.unep.ch/dev/test to do their tests. What is the new URL: https://www.mapx.io/app/w10/#sectionMap ?

**Comment by fxi** [comment]
Give them simply mapx.io. If there is some specific test to do, I will provide the full url, like https://mapx.io/app/new_feature_to_test

From my point of view, for experimental and unstable features, we should test them locally and report issues here. As soon as a stable version is released, we can include an external team to test again. We have to make sure that external testers report any issues or features request in this issue tracker.
