### ISSUE TITLE
change order of class in view explorer

### ISSUE THREAD

**Issue by fxi** [fxi/map-x-shiny#17]
extractive
development
social
environment
stresses

**Comment by PierreLacroix** [comment]
Deadline Friday 20 May 2016

**Comment by PierreLacroix** [comment]
1) 'MES AYNAK AREA' should be put at lowest (after 'STRESSES') and be renamed 'PILOT SITES'
2) Ultimately we could have subcategories into this category (subcategory MES AYNAK, subcategory AMANIA and category KAHSKARI). What is the feasibility of having this for Friday 20 May? Or later?

**Comment by fxi** [comment]
Ordering: done.  The order is given in the configuration file, postgres sort the views with that order and the ui display the result.
Pilote sites : done.
Subcategory: not possible for today. If you have a specific structure in mind, we have to write a clear specification, because once the logic is created, it's not trivial to change something. 
Note : all changes are done in pg_users branch. It will be merged as soon as possible with master.
You can close this issue if everything is ok.

**Comment by PierreLacroix** [comment]
OK you can close, thanks
