### ISSUE TITLE
Opening Excel makes the application greyed

### ISSUE THREAD

**Issue by PierreLacroix** [fxi/map-x-shiny#2]
01.FEB.2016 tested on mapx.io/test by Pierre
Opening or downloading Excel (reconciliation file) greys the application. It is still possible to use the application
This issue is not critical

**Comment by fxi** [comment]
Application is grayed = disconnected. Which is related to an error server side or a disconnection from the user. The session is closed and no interaction client-server will be handled.

Could you provide the browser and OS used ? Did the browser opened a new window (or tab) for downloading or the same window was used ?

Thanks

**Comment by PierreLacroix** [comment]
Firefox 43.0.4 on Mac 10.10.5 Yosemite -> opens a new window (see attachment)
Tested also from Safari 9.0 -> the problem does not occur with Safari. No new Windows is opened
<img width="1202" alt="screen shot 2016-02-01 at 13 27 57" src="https://cloud.githubusercontent.com/assets/6863326/12717361/a7f77b34-c8e7-11e5-9a2c-12d0d46b5843.png">

**Comment by fxi** [comment]
Ok, I was able to reproduce this. The websocket is broken: this is a bug from firefox. And the download attribute from <a> does not seems to be honored with data from a different origin (e.g. your server). Quite annoying, especially if we don't want a new window to be opened (target="_blank").

Those files could be integrated to www/data ? It could solve the "same origin" part of the problem ..

**Comment by PierreLacroix** [comment]
OK please integrate the Excel files to www/data to solve this part of the problem. Same for the 2014 report

**Comment by fxi** [comment]
Target "_blank" with download attribute solved this issue.
