### ISSUE TITLE
RGI graph display

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-shiny#25]
In the country profil, RGI graph displays superimposed data for several countries at once.
When moving the cursor over the graph, the data displayed vary from one country to another. These changes don't affect the key metrics, abstract or WDI part of the country profil.

![rgi_3_cut](https://cloud.githubusercontent.com/assets/19908801/16007767/aa2f9cba-3174-11e6-8617-6437420df04e.JPG)

Firefox 47.0, windows 7 pro 64 bit

**Comment by fxi** [comment]
This should be solved.
