### ISSUE TITLE
OK button position on metadata window

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-shiny#26]
If one moves the metadata window with the mouse, the OK button changes position and moves out of the window. There are also side scroll bars that are displayed and which are not very aesthetic.

![icone_ok_cut](https://cloud.githubusercontent.com/assets/19908801/16008099/7b5ed6ba-3176-11e6-84e3-9ecdc197600b.JPG)

Firefox 47.0, windows 7 pro 64 bit

**Comment by fxi** [comment]
It should be ok now. 
New feature : a button bellow zoom bar ➕ / ➖  containing an info logo ℹ️  enable a new querying mode.
Please close it if everything is ok.
