### ISSUE TITLE
Layer description remains displayed

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-shiny#27]
The description of the layers is not displayed when you leave the mouse cursor over them. Sometimes, it does but the insert remains displayed all the time.

![description_cut](https://cloud.githubusercontent.com/assets/19908801/16008426/3caa0532-3178-11e6-8585-fafdc1e74759.JPG)

Firefox 47.0, windows 7 64 bit

**Comment by fxi** [comment]
This does not exist anymore, I close it.
