### ISSUE TITLE
Polygon of interest output

### ISSUE THREAD

**Issue by thomaspiller** [fxi/map-x-shiny#28]
Polygon of interest doesn't transmit the data selected on the screen.

![polyofinterest](https://cloud.githubusercontent.com/assets/19908801/16042571/aa5c0166-323b-11e6-8251-58b4c6753584.JPG)

Firefox 47.0 & Chrome 51, windows 7 64 bit

**Comment by fxi** [comment]
It's fixed, but there is a new one: the temporary layer is not found. 
I will update in this thread.

**Comment by fxi** [comment]
Ok. Gdal binaries were not installed. Should be ok now : I've updated the vagrant provision and updated the online version. Please test on your side and close if this is solved.
