### ISSUE TITLE
Pictures are not attached to contamination points

### ISSUE THREAD

**Issue by PierreLacroix** [fxi/map-x-shiny#3]
01.FEB.2016 tested on mapx.io/test by Pierre
Pictures are not attached to the contamination points.
This issue is not critical but should be solved for Lima (23 FEB)

**Comment by fxi** [comment]
Thanks.
I will add an option in package leafletvt to handle special case such as image or html with an onclick event.

**Comment by fxi** [comment]
done. live preview on mapx.io/test and new katanga data. If a .jpg is read in the string of an attribute, leafletvt will try to return a leaflet popup containing an `<img>`.
