### ISSUE TITLE
Text panel in Story Editor can grow outside its "frame"

### ISSUE THREAD

**Issue by NikosAlexandris** [fxi/map-x-shiny#8]
![mapx_story_editor_edit_panel_outside_of_frame](https://cloud.githubusercontent.com/assets/7046639/13199071/2802bfae-d81b-11e5-9b82-e19ef86c2cac.jpg)

The screenshot is self-explaining. Under Firefox 42.0. Did not test via other browsers.

**Comment by fxi** [comment]
It should work now. 
Please close this if it's ok.
